<h3>Задание 1</h3>

In [1]:
import pandas as pd

In [11]:
movies = pd.read_csv('movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [12]:
ratings = pd.read_csv('ratings.csv')
ratings.head()

   userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264

In [32]:
(
    ratings[ ratings.rating == 5.0 ][['movieId', 'rating']]
    .groupby('movieId').count().sort_values('rating', ascending = False)
    .merge(movies[['movieId', 'title']], on = 'movieId', how = 'left')
    [['movieId', 'title', 'rating']]
)[0:1]

   movieId                             title  rating
0      318  Shawshank Redemption, The (1994)   48762

<h3>Задание 2</h3>

In [34]:
power = pd.read_csv('power.csv')
power.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [52]:
summed = (
    power[ (power.quantity >= 0) & (power.year >= 2005) & (power.year <= 2010) & 
          (power['country'].isin(['Lithuania', 'Latvia', 'Estonia'])) &
          (power['category'].isin([4, 12, 21]))]
    [['country', 'quantity']]
)

summed['region'] = 'Baltic'

summed.groupby('region').sum()

        quantity
region
Baltic  240580.0

<h3>Задание 3</h3>

In [72]:
page = pd.read_html('https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8', 
                    attrs = {'class': 'wikitable'})

In [73]:
page

[                            Население  1678 год       1719 год       \
                    Unnamed: 0_level_1 Млн, чел.    % Млн, чел.    %
 0                     Феодалы и армия        03    6         5    6
 1                          Крепостные        34   60        47   60
 2  Феодально-зависимые от государства        11   19        16   21
 3                               ИТОГО        48   85        68   87
 4                Левобережная Украина        08   15         7    9
 5                          Прибалтика         —    —         3    4
 6                               ВСЕГО        56  100        78  100

                Прирост (естественный и механический)
                                   Unnamed: 5_level_1
 0                                                 02
 1                                                 13
 2                                                 05
 3                                                 20
 4  -1Уменьшение численности населения произошло, ...
 5                                                 03
 6                                                 22  ,
     Годы Всё население Городское население Сельское население
 0   1950     2 745 997           1 171 250          1 574 747
 1   1960     2 782 353           1 332 812          1 449 541
 2   1970     1 903 713           1 205 207            698 506
 3   1980     2 202 779           1 535 723            667 056
 4   1990     1 988 858           1 386 247            602 611
 5   1995     1 363 806             933 460            430 346
 6   2000     1 266 800             886 908            379 892
 7   2001     1 311 604             928 642            382 962
 8   2002     1 396 967             998 056            398 911
 9   2003     1 477 301           1 050 565            426 736
 10  2004     1 502 477           1 074 247            428 230
 11  2005     1 457 376           1 036 870            420 506
 12  2006     1 479 637           1 044 540            435 097
 13  2007     1 610 122           1 120 741            489 381
 14  2008     1 713 947           1 194 820            519 127
 15  2009     1 761 687           1 237 615            524 072
 16  2010     1 788 948           1 263 893            525 055
 17  2011     1 796 629           1 270 047            526 582
 18  2012     1 902 084           1 355 674            546 410
 19  2013     1 895 822           1 357 310            538 512
 20  2014     1 942 683           1 394 860            547 823
 21  2015     1 940 579           1 455 283            485 296
 22  2016     1 888 729           1 426 591            462 138
 23  2017     1 690 307           1 269 527            420 780
 24  2018     1 604 344           1 205 231            399 113
 25  2019     1 481 074           1 115 337            365 737,
          Годы  Всё население  Городское население  Сельское население
 0   1960—1961           2540                 2040                3320
 1   1961—1962           2417                 1935                3195
 2   1962—1963           2311                 1847                3098
 3   1963—1964           2227                 1782                3026
 4   1964—1965           2139                 1732                2928
 5   1965—1966           2125                 1728                2974
 6   1966—1967           2072                 1707                2898
 7   1967—1968           1998                 1677                2746
 8   1968—1969           1975                 1696                2627
 9   1969—1970           1972                 1733                2535
 10  1970—1971           2007                 1773                2588
 11  1971—1972           2053                 1825                2656
 12  1972—1973           2023                 1800                2660
 13  1973—1974           2000                 1770                2704
 14  1974—1975           1993                 1757                2764
 15  1975—1976           1969                 1734                2779
 16  1976—1977           1967                 1737                2773
 17  1977—1978           1938                 1717                2734
 18  1978—1979           1902                 1714                2497
 19  1979—1980           1888                 1698                2504
 20  1980—1981           1895                 1700                2562
 21  1981—1982           1951                 1739                2758
 22  1982—1983           2047                 1820                2910
 23  1983—1984           2083                 1850                2988
 24  1984—1985           2057                 1826                2936
 25  1985—1986           2111                 1874                3003
 26  1986—1987           2194                 1947                3162
 27       1988           2130                 1896                3057
 28       1989           2007                 1826                2630
 29       1990           1892                 1698                2600
 30       1991           1732                 1531                2447
 31       1992           1547                 1351                2219
 32       1993           1360                 1195                1913
 33       1994           1385                 1234                1884
 34       1995           1337                 1193                1813
 35       1996           1270                 1140                1705
 36       1997           1212                 1094                1603
 37       1998           1232                 1109                1643
 38       1999           1157                 1045                1534
 39       2000           1195                 1089                1554
 40       2001           1223                 1124                1564
 41       2002           1286                 1189                1633
 42       2003           1319                 1223                1666
 43       2004           1344                 1253                1654
 44       2005           1294                 1207                1576
 45       2006           1305                 1210                1601
 46       2007           1416                 1294                1798
 47       2008           1502                 1372                1912
 48       2009           1542                 1415                1941
 49       2010           1567                 1439                1983
 50       2011           1582                 1442                2056
 51       2012           1691                 1541                2215
 52       2013           1707                 1551                2264
 53       2014           1750                 1588                2318
 54       2015           1777                 1678                2111
 55       2016           1760                 1671                2060
 56       2017           1621                 1527                1923
 57       2018           1579                 1489                1870
 58       2019           1504                 1427                1754,
     Год Родилось, чел. Умерло, чел. Естественный прирост (+) или убыль (−)  \
 0  2011      1 796 629    1 925 720                               −129 091
 1  2012      1 902 084    1 906 335                                 −4 251
 2  2013      1 895 822    1 871 809                                 24 013
 3  2014      1 942 683    1 912 347                                 30 336
 4  2015      1 940 579    1 908 541                                 32 038
 5  2016      1 893 256    1 887 913                                  5 343
 6  2017      1 689 884    1 824 340                               −134 456
 7  2018      1 604 344    1 828 910                               −224 556
 8  2019      1 481 074    1 798 307                               −317 233

   Миграционный прирост, чел.  \
 0                    320 100
 1                    294 930
 2                    231 061
 3                    216 900
 4                    219 748
 5                    261 948
 6                    211 880
 7                    124 844
 8                    285 103

                                          Комментарии
 0                                                NaN
 1  Естественный прирост в 2012 году отмечен в 40 ...
 2  Естественный прирост в 2013 году отмечен в 43 ...
 3  Естественный прирост в 2014 году отмечен в 43 ...
 4  Естественный прирост в 2015 году отмечен в 43 ...
 5  Естественный прирост в 2016 году отмечен в 39 ...
 6  Естественный прирост в 2017 году отмечен в 31 ...
 7  Естественный прирост в 2018 году отмечен в 21 ...
 8  Естественный прирост в 2019 году зафиксирован ...  ,
     Годы Численность населения (тыс. чел.) Количество родившихся (тыс. чел.)  \
 0   1927                            93 604                             4 688
 1   1928                            95 587                             4 723
 2   1929                            97 721                             4 633
 3   1930                            99 566                             4 413
 4   1931                           101 272                             4 412
 5   1932                           102 624                             4 058
 6   1933                           103 648                             3 313
 7   1934                           101 763                             2 923
 8   1935                           102 080                             3 577
 9   1936                           103 288                             3 899
 10  1937                           104 520                             4 377
 11  1938                           106 195                             4 379
 12  1939                           107 892                             4 329
 13  1940                           109 678                             3 814
 14  1941                           110 988                             3 650

    Количество умерших (тыс. чел.) Естественный прирост (тыс. чел.)  \
 0                           2 705                            1 983
 1                           2 589                            2 134
 2                           2 819                            1 814
 3                           2 738                            1 675
 4                           3 090                            1 322
 5                           3 077                              981
 6                           5 239                           −1 926
 7                           2 659                              264
 8                           2 421                            1 156
 9                           2 719                            1 180
 10                          2 760                            1 617
 11                          2 739                            1 640
 12                          2 600                            1 729
 13                          2 561                            1 253
 14                          2 283                            1 367

     Общий коэффициент рождаемости (на 1000)  \
 0                                      4904
 1                                      4833
 2                                      4653
 3                                      4358
 4                                      4299
 5                                      3915
 6                                      3256
 7                                      2863
 8                                      3463
 9                                      3730
 10                                     4122
 11                                     4059
 12                                     3947
 13                                     3436
 14                                     3250

     Общий коэффициент смертности (на 1000)  \
 0                                     2830
 1                                     2649
 2                                     2831
 3                                     2704
 4                                     3011
 5                                     2969
 6                                     5148
 7                                     2605
 8                                     2344
 9                                     2601
 10                                    2599
 11                                    2539
 12                                    2371
 13                                    2307
 14                                    2033

    Общий коэффициент естественного прироста[63]  \
 0                                          2074
 1                                          2184
 2                                          1822
 3                                          1654
 4                                          1288
 5                                           946
 6                                        −18,93
 7                                           259
 8                                          1119
 9                                          1129
 10                                         1523
 11                                         1520
 12                                         1576
 13                                         1129
 14                                         1217

     .mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}СКР  \
 0                                              6653.0
 1                                              6534.0
 2                                              6201.0
 3                                              5785.0
 4                                              5611.0
 5                                              5042.0
 6                                              4069.0
 7                                              3586.0
 8                                              4259.0
 9                                              4554.0
 10                                             5047.0
 11                                             4987.0
 12                                             4881.0
 13                                             4252.0
 14                                                NaN

     ОПЖ (м)  ОПЖ (ж)
 0     337.0    379.0
 1     359.0    404.0
 2     337.0    382.0
 3     346.0    387.0
 4     307.0    355.0
 5     305.0    357.0
 6     152.0    195.0
 7     305.0    357.0
 8     331.0    384.0
 9     304.0    357.0
 10    305.0    400.0
 11    317.0    425.0
 12    349.0    426.0
 13    357.0    419.0
 14      NaN      NaN  ,
      Год Численность населения на 1 января Количество родившихся  \
 0   1946                        97 548 000             2 546 000
 1   1947                        98 028 000             2 715 000
 2   1948                        98 834 000             2 516 000
 3   1949                        99 706 000             3 089 000
 4   1950                       101 160 000             2 859 000
 5   1951                       102 833 000             2 938 000
 6   1952                       104 439 000             2 928 000
 7   1953                       106 164 000             2 822 000
 8   1954                       107 828 000             3 048 000
 9   1955                       109 643 000             2 942 000
 10  1956                       111 572 000             2 827 000
 11  1957                       113 327 000             2 880 000
 12  1958                       115 035 000             2 861 000
 13  1959                       116 749 000             2 796 228
 14  1960                       118 307 000             2 782 353
 15  1961                       119 906 000             2 662 135
 16  1962                       121 586 000             2 482 539
 17  1963                       123 128 000             2 331 505
 18  1964                       124 514 000             2 121 994
 19  1965                       125 744 000             1 990 520
 20  1966                       126 749 000             1 957 763
 21  1967                       127 608 000             1 851 041
 22  1968                       128 361 000             1 816 509
 23  1969                       129 037 000             1 847 592
 24  1970                       129 660 000             1 903 713
 25  1971                       130 252 000             1 974 637
 26  1972                       130 934 000             2 014 638
 27  1973                       131 687 000             1 994 621
 28  1974                       132 434 000             2 079 812
 29  1975                       133 217 000             2 106 147
 30  1976                       134 092 000             2 146 711
 31  1977                       135 026 000             2 156 724
 32  1978                       135 979 000             2 179 030
 33  1979                       136 922 000             2 178 542
 34  1980                       137 758 000             2 202 779
 35  1981                       138 483 000             2 236 608
 36  1982                       139 221 000             2 328 044
 37  1983                       140 067 000             2 478 322
 38  1984                       141 056 000             2 409 614
 39  1985                       142 061 000             2 375 147
 40  1986                       143 033 000             2 485 915
 41  1987                       144 156 000             2 499 974
 42  1988                       145 386 000             2 348 494
 43  1989                       146 505 000             2 160 559
 44  1990                       147 665 081             1 988 858
 45  1991                       148 273 746             1 794 626

    Количество умерших Естественный прирост Общий прирост населения  ОКР  ОКС  \
 0           1 210 000            1 336 000                     NaN  260  123
 1           1 680 000            1 035 000                     NaN  275  170
 2           1 310 000            1 206 000                     NaN  252  131
 3           1 187 000            1 902 000                     NaN  305  117
 4           1 180 000            1 679 000                     NaN  278  115
 5           1 210 000            1 728 000                     NaN  281  116
 6           1 138 000            1 790 000                     NaN  276  107
 7           1 118 000            1 704 000                     NaN  262  104
 8           1 133 000            1 915 000                     NaN  278  103
 9           1 037 000            1 905 000                     NaN  264   93
 10            956 000            1 871 000                     NaN  249   84
 11          1 017 000            1 863 000                     NaN  250   88
 12            931 000            1 930 000                     NaN  245   80
 13            920 225            1 876 003                     NaN  236   78
 14            886 090            1 896 263                     NaN  232   74
 15            901 637            1 760 498                     NaN  219   74
 16            949 648            1 532 891                     NaN  202   77
 17            932 055            1 399 450                     NaN  187   75
 18            901 751            1 220 243                     NaN  169   72
 19            958 789            1 031 731                     NaN  157   76
 20            974 299              983 464                     NaN  153   76
 21          1 017 034              834 007                     NaN  144   79
 22          1 040 096              776 413                     NaN  141   81
 23          1 106 640              740 952                     NaN  142   85
 24          1 131 183              772 530                     NaN  146   87
 25          1 143 359              831 278                     NaN  151   87
 26          1 181 802              832 836                     NaN  153   90